# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
       - image: circleci/ruby:latest-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: sudo npm install -g allure-commandline --save-dev
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: generate report
          command: |
            allure generate gen/allure-results
      # collect reports
      - store_test_results:
          path: /gen/allure-results
      - store_artifacts:
          path: /gen/allure-results
          destination: /gen/allure-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - test