# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
       - image: circleci/ruby:latest-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: sudo npm install -g allure-commandline --save-dev
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            "${TEST_FILES}"

      - run:
          name: show directory
          command: pwd
      - run:
          name: generate report
          command: allure generate gen/allure-results
      # collect reports
      - store_test_results:
          path: /build/
      - store_artifacts:
          path: /gen/allure-results
      - store_artifacts:
          path: /allure-report

workflows:
  version: 2
  build_and_test:
    jobs:
      - test